FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="Object Storage Sample Driver"

COPY ./bin/objectstorage-sample-driver objectstorage-sample-driver
ENTRYPOINT ["/objectstorage-sample-driver"]
